sudo: true
cache: false
language: android
jdk: oraclejdk8

env:
  global:
      MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  apt_packages:
    - pandoc

script: ./gradlew build


after_failure:
  - pandoc app/build/reports/tests/release/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  - pandoc notificationsengine/build/reports/tests/release/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_success:
- ./gradlew connectedAndroidTest coveralls

after_script:
- for f in "app/build/outputs/lint-results*.html"; do pandoc $f -t plain; done
- for f in "notificationsengine/build/outputs/lint-results*.html"; do pandoc $f -t plain; done